### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'end'

### ISSUE THREAD

**Issue by swlong** [scwatts/hicap#2]
Running v.1.0.1 now, fixed my issue for most of the files but 3 of them threw a new error. Apologies again for the screenshot: 

![hicap-screen2](https://user-images.githubusercontent.com/2158927/59124590-ba114500-8925-11e9-8e4a-2ea4e8876fbf.JPG)

I will email an example assembly that caused the error. 

Best,
S. Wesley Long

**Comment by scwatts** [comment]
I believe I've fixed this issue as well. The underlying problem was in calculating contig hit bounds for the output file where the bounds were defined by a BLAST-only hit (i.e. a hit without an ORF). Having a BLAST-only hit is fairly rare and having it at the contig hit bound even more so!

I'll publish v1.0.2 with this fix but I'll wait a couple of days before updating the conda recipe in case there are some more corner cases for us to catch. Thanks again for opening an issue and provided the assemblies.
