### ISSUE TITLE
output questions

### ISSUE THREAD

**Issue by yonglixiao** [scwatts/hicap#9]
Hi there,

Recently, I used hicap to predict serotype of an obtained S. pyogenes sequence. I have two questions about the output.

1. In the 'genes_identified' column of my hicap output, some genes are marked with a "^". I don’t know what does that mean and it is not in the documentation. 
2. In ‘region_II_genes’ column, I got “1/3 (missing: fcs3,fcs2)”. However, in 'genes_identified' column, it contains “fcs3^,fcs2^,fcs2^”. My question is: are fcs3 and fcs2 missing or identified in my search? Why are there 2 "fcs2^"?

Thanks,

Yongli Xiao

**Comment by scwatts** [comment]
Hi @yonglixiao, thanks for choosing to use hicap! While hicap is designed only to work with _H. influenzae_, I am pleased to hear you have been able to generate results for _S. pyogenes_ though admittedly somewhat surprised this does work.

To answer your questions:

1. genes marked with the caret symbol (^) are those that have sequence identity matches according to BLAST but had no ORF predicted by Prodigal
1. genes are only considered found (not missing) when they have both a high quality BLAST hit to a reference gene and a valid ORF. The identified genes shown all have BLAST hits but no ORFs hence these genes are considered missing - in this scenario all candidate BLAST hits are also returned so that they can be manually reviewed, hence the multiple 'fcs2' entries.
